
services:
  frontend:
    build: .
    image: pavlo-systems-frontend
    ports:
      - "3245:4173"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: pavlo-systems-backend
    ports:
      - "7654:8080"
    depends_on:
      - db-test
      
  db-test:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedback
    ports:
      - "9876:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: